name: ZombieArenaPlugin
version: ${version}
main: io.github.josseboxnice.zombieArenaPlugin.zombieArenaPlugin
description: Plugin for zombie arena minigame server
author: Joosua Virtanen
api-version: "26.3"
